trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: '<TU-SERVICE-CONNECTION-SI-USAS-ACR>'
  dockerComposeFile: 'docker-compose.yml'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '8'
    jdkArchitecture: 'x64'

- task: DockerCompose@0
  displayName: 'Build and Push containers'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: $(dockerComposeFile)
    action: 'Build services'
    additionalDockerComposeFiles: ''
    buildImages: |
      users-api
      auth-api
      todos-api
      log-message-processor
      frontend

- task: DockerCompose@0
  displayName: 'Run containers'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: $(dockerComposeFile)
    action: 'Run services'

