version: '3.8'

services:

  users-api:
    image: ghcr.io/solosoyjuan/users-api:sha-0e0712f
    ports:
      - "8083:8083"
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
    networks:
      - msa-network

  auth-api:
    image: ghcr.io/solosoyjuan/auth-api:sha-0e0712f
    ports:
      - "8000:8000"
    environment:
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=PRFT
    depends_on:
      - users-api
    networks:
      - msa-network

  todos-api:
    image: ghcr.io/solosoyjuan/todos-api:sha-0e0712f
    ports:
      - "8082:8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - msa-network

  frontend:
    image: ghcr.io/solosoyjuan/frontend:sha-0e0712f
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
    depends_on:
      - auth-api
      - todos-api
    networks:
      - msa-network

  log-message-processor:
    image: ghcr.io/solosoyjuan/log-message-processor:sha-0e0712f
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - msa-network

  redis:
    image: redis:7.0
    ports:
      - "6380:6379"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
