name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Publish to Docker"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Este es un workflow de despliegue. Aún no está conectado a la EC2."
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/deploy"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/deploy
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u solosoyjuan --password-stdin
            docker-compose pull
            docker-compose up -d --force-recreate
