name: Publish to Docker

on:
  pull_request:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # auth-api
      - name: Docker meta auth-api
        id: meta-auth-api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/solosoyjuan/auth-api
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push auth-api
        uses: docker/build-push-action@v5
        with:
          context: ./auth-api
          push: true
          tags: ${{ steps.meta-auth-api.outputs.tags }}

      # frontend
      - name: Docker meta frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/solosoyjuan/frontend
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}

      # log-message-processor
      - name: Docker meta log-message-processor
        id: meta-log
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/solosoyjuan/log-message-processor
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push log-message-processor
        uses: docker/build-push-action@v5
        with:
          context: ./log-message-processor
          push: true
          tags: ${{ steps.meta-log.outputs.tags }}

      # todos-api
      - name: Docker meta todos-api
        id: meta-todos
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/solosoyjuan/todos-api
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push todos-api
        uses: docker/build-push-action@v5
        with:
          context: ./todos-api
          push: true
          tags: ${{ steps.meta-todos.outputs.tags }}

      # users-api
      - name: Docker meta users-api
        id: meta-users
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/solosoyjuan/users-api
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push users-api
        uses: docker/build-push-action@v5
        with:
          context: ./users-api
          push: true
          tags: ${{ steps.meta-users.outputs.tags }}
